pipeline {
    agent any

    stages {
        stage('deploy') {
                steps {
                    // Run the docker-compose
                    sh 'ls'
                    sh 'pwd'
                    sh 'docker-compose up'
                }
            }
    }
}