pipeline {
    agent any

    stages {
        stage('deploy') {
                steps {
                    // Run the docker-compose
                    sh 'cd cd/docker/'
                    sh 'docker-compose up'
                }
            }
    }
}