pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the GitHub repository
                git url: 'https://github.com/Mohmedahmeed/GitOps.git', branch: 'main'
            }
        }
        stage('deploy') {
                steps {
                    // Run the docker-compose
                    sh 'ls'
                    sh 'pwd'
                    sh 'docker-compose -f GitOps/cd/docker/docker-compose.yml up'
                }
            }
    }
}